apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ebs-po
spec:
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: pv-pod
          

    