apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ebs-po
  labels:
    app: pv-pod
spec:
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
